### ISSUE TITLE
Found some issues.

### ISSUE THREAD

**Issue by MagmaBro123** [efeketket/Furnicraft#17]
- Some furniture cant be removed if you break them in the wrong spots. (If barriers are missing, delete the block. Don't leave stuff behind.)
- Furniture Skulls can be placed where furniture already exists.
- Sometimes placing furniture too fast will cause the Furniture Skull to not turn into furniture.
- Corner sofas are not possible.
- Lamp blocks are non-functional, no Soul variant exists. (See image below.)

Some suggestions:

- If any wool is added while a wooden furniture is being made, a version of the furniture with wool bits should be outputted instead.
- Gold and Copper Poles, with matching lanterns.

Otherwise, amazing pack.

(An item frame pops out too.)
![2024-11-05_14 14 51](https://github.com/user-attachments/assets/ffa655d7-27a8-48d3-a065-e65334392956)

**Comment by MagmaBro123** [comment]
@efeketket Almost a month later. Please respond, or remove this pack if you have no interest in it.

**Comment by efeketket** [comment]
Thank you for your feedback and suggestions! I'm currently swamped with schoolwork, but I wanted to address your points carefully during my free time. Sorry for the delay!

* About the furniture breaking issue: It should automatically break when the dependency block is broken—I've just tested this. Could you specify which furniture bugged?
* Regarding placing skulls on furniture: I made it so that skulls can be placed on existing furniture without breaking. This prevents the loss of custom data when the skulls are broken. Additionally, this allows players to use multiple pieces of furniture together in one block.
* As for the furniture not transforming immediately when placed: Yes, this is a known issue. I'm working to improve the detection. For a quick fix, if the furniture piece doesn't transform right after placing, try moving your head slightly to look directly at it this will fix it. It just takes 0.5 sec. 
* Corner sofas were initially implemented but removed for optimization. I plan to reintroduce them once I've sorted out other priorities.
* Noted your suggestion about the lamp. Perhaps I'll add a Soul variant; we'll see.
* Regarding adding colored furniture, more wooled furniture: I'm already working on it, though it's complex due to the wide variety of items already in the pack. Adding more variants would make the pack little bit complex.

**Comment by efeketket** [comment]
I appreciate that people are interested in my projects and help me to develop them. I'm already doing my best to improve my project. It's not your business to decide whether to remove it. Have a nice day!

**Comment by MagmaBro123** [comment]
> Thank you for your feedback and suggestions! I'm currently swamped with schoolwork, but I wanted to address your points carefully during my free time. Sorry for the delay!
> 
> * About the furniture breaking issue: It should automatically break when the dependency block is broken—I've just tested this. Could you specify which furniture bugged?
> * Regarding placing skulls on furniture: I made it so that skulls can be placed on existing furniture without breaking. This prevents the loss of custom data when the skulls are broken. Additionally, this allows players to use multiple pieces of furniture together in one block.
> * As for the furniture not transforming immediately when placed: Yes, this is a known issue. I'm working to improve the detection. For a quick fix, if the furniture piece doesn't transform right after placing, try moving your head slightly to look directly at it this will fix it. It just takes 0.5 sec.
> * Corner sofas were initially implemented but removed for optimization. I plan to reintroduce them once I've sorted out other priorities.
> * Noted your suggestion about the lamp. Perhaps I'll add a Soul variant; we'll see.
> * Regarding adding colored furniture, more wooled furniture: I'm already working on it, though it's complex due to the wide variety of items already in the pack. Adding more variants would make the pack little bit complex.

What about the lsaamp placement issue?
