### ISSUE TITLE
Downloaded the mod and datapack, but no option to craft items - and they don't show in creative

### ISSUE THREAD

**Issue by jennandtonic105** [efeketket/Furnicraft#6]
I have downloaded the mod and datapack, and when I log on to either a creative world or a survival world with them loaded, upon initial log in I get the notification that the advancements have been added - but I do not have the option to see any of these items in creative.

Also, I have vanilla tweaks, the redstone wrench datapack -  even though the recipe for the wrench is not the same, when I try to craft the carpenter's bench with the stated recipe (wood, shears, and an axe) it only gives the option to craft the wrench. When I deactivate the wrench datapack I do get the option to craft the bench. Is there any way to change the item ID or anything to make the two compatible?

**Comment by efeketket** [comment]
Hey! Thank you for your time to feedback. First with datapack mechanic, its not possible to add items to creative item list. I'm currently working on a new furniture catalog to make it easier for creative players to get furniture. For now you can get furniture items with "loot" command.

For crafting thing, i understand that, wrench u mention do not have "pattern" parameter. It means its not important to craft wrench to exactly where u placed materials. Because of that, when it enabled, it overwrites carpenter bench recipe. If you add it, it can fix problem.


It look like this. for carpenter bench. You can customize it for the wrench recipe. Just add this with customisations to wrench recipe. It located in the folder "<wrench-datapack-folder-name>/data/<datapack-namespace>/recipe".
 ```
    "pattern": [
        "#S",
        "OO",
        "OO"
    ],
    "key": {
        "#": {
            "tag": "minecraft:axes"
        },
        "S": {
            "item": "minecraft:shears"
        },
        "O": {
            "tag": "minecraft:planks"
        }
 ```

**Comment by jennandtonic105** [comment]
Got it fixed, thank you! That was very helpful. And, noted on the loot command - will use that moving forward. I didn't realize they don't allow datapacks in creative mode - I thought I had used them in creative before (other furniture mod that was nowhere near as polished as yours) but I was probably mistaken!

**Comment by efeketket** [comment]
Glad it worked out. The items u mention may have been added to the creative menu with mod. I'll look for it. Thanks for your time. Have a nice day!

**Comment by jennandtonic105** [comment]
> Glad it worked out. The items u mention may have been added to the creative menu with mod. I'll look for it. Thanks for your time. Have a nice day!

Maybe so!  And it's been awhile. At any rate I much prefer your datapack/mod. Thank you so much for putting this together!
